spring.data.mongodb.uri=mongodb://localhost:27017/habit_tracker
spring.application.name=DailyHabitTracker
server.port=8080

spring.data.mongodb.database=habit_tracker
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
